### This file supports bash-style comments, and blank lines.
### PKGs on same line will be sent to `yay` together, unless `-f` is specified.

### Most dependencies have been moved to meta packages as declared in arch-packages.
### Use this file for declaring extra dependencies which you need but are not declared by default.

nano
fastfetch
git
nautilus
gnome-system-monitor
noto-fonts-emoji noto-fonts-cjk
thorium-browser-bin
visual-studio-code-bin
steam
termius
vi
vesktop-bin
plex-desktop
slack-desktop
coolercontrol-bin